version: '3.8'

services:
  server:
    build:
      context: server
    environment:
      - DB=mongodb://mongodb:27017/notely
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    volumes:
      - .:/src
    networks:
      - node-network
    command: npm start
  client:
    build:
      context: client
    ports:
      - 3000:3000
    networks:
      - node-network
    command: npm start
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - node-network

volumes:
  dbdata6:

networks:
  node-network:
    driver: bridge